### PR TITLE
Add HostGamePage, socket.io integration, and game states.

### PR DESCRIPTION
**Pull request by jnarezo**
Adds match components (with boilerplate state info).
Switch to CSS Modules and Sass (node-sass).
Add global app styles (font, theme colors, background).

New containers:

- `HostGameView`: Presents the Host's in-game view, intended for use in `App.js`. Currently a mock-up.

New components:

- `MatchInfo`: A header for the top of the screen. Displays the player's Room ID, nickname, and current question.
- `BarGraph`: A bar graph, with up to 4 buckets/bars.
- `Bar`: A bar for the bar graph that displays a number above it corresponding to the property `count`.
    - `count`: Adjusts the bar's height and number above.
    - `shape`: Colors the corresponding to the answer shape given.
- `QuestionCard`: A larger card attached to the left of the screen. Displays the question along with its number.
    - `shape`: Displays a shape (rather than question number) and applies a color corresponding to the answer shape given.
- `AnswerCard`: A basic card that displays text and shape related to the property `shape`.
    - `shape`: Displays a shape and applies a color corresponding to the answer shape given.
    - `disabled`: Applies a dimmer style to the card. Compatible with `shape`.
- `TriangleAnswer`: An AnswerCard with the `shape='triangle'` prop.
- `StarAnswer`: An AnswerCard with the `shape='star'` prop.
- `CircleAnswer`: An AnswerCard with the `shape='circle'` prop.
- `SquareAnswer`: An AnswerCard with the `shape='square'` prop.

Screenshot_8
Screenshot_9

### CODE REVIEW

**Comment by anh65498** [comment]
I'm a little confused. When I run your code, I don't see anything but a blank page. Inside your < App />, you aren't displaying any component so essentially, the client doesn't run anything that you wrote. How should I review your code when all I see is a blank page?

**Comment by jnarezo** [comment]
Without the routers in place, it might be difficult to juggle the mock-up placed in the app throughout future commits. I'll add a mock-up for this branch's components, though I'm unsure how I should actually present new components in the future.

**Comment by anh65498** [comment]
Are you waiting for Ishaan to finish adding the routes to add your routes to render components? If so, I shall move back your issue to `In Progress` column. In the future, please add your routes to < App > or < Main > along with rendering your components so it's easy for me to review the work. What I suggest is to follow the user flow to add routes and components one by one.

**Review by anh65498 — APPROVED** [review]
I can't get it to work on my computer so let's merge yours into develop and see if it works

**Pull request merged**
